[package]
name = "joann"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
space = "0.18.0"

[dev-dependencies]
microbench = "0.5.0"
