[package]
name = "joann"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.18"
memmap2 = "0.9.4"
rand = "0.8.5"
smallbitvec = "2.5.1"

[dev-dependencies]
microbench = "0.5.0"